# Generated by Django 5.0.1 on 2024-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shearing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textshearing',
            name='urls',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textshearing',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
